name: Bug Report
description: File a bug report.
title: "[BUG]: "
labels: ["bug", "question"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report. We'll use this information to help us fix the issue you're experiencing. Please fill out the following information to the best of your ability.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us with details what happened.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/VitorM3/Ecommerce-ED/blob/main/CODE_OF_CONDUCT.md). 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true